### ISSUE TITLE
Is there any short guide steps for running bpf_uvm

### ISSUE THREAD

**Issue by Elio-yang** [vchuravy/bpf_uvm#1]
Hi,

I am just starting to explore BPF and Julia, and I find this project very interesting. I am familiar with GPU drivers and UVM, but not BPF and Julia. Therefore, I've checked the history of the readme file. Do the steps mentioned in the previous readme still work? Or could you please provide a short guideline for running bpf_uvm?

Thanks.

**Comment by vchuravy** [comment]
Not really, This was all rather specific to my current system at the time.

In theory you should be able to run `python uvm.py` (sadly never managed to rewrite it to use BPFNative.jl) and then in a seperate process run `julia test-uvm.jl`, but `uvm.c` duplicates data from driver specific things so that may have changed on a different driver version.

**Comment by Elio-yang** [comment]
It helps, thanks for the reply :)
